import { SILENCED } from '../core/off.js';
import { readdir, open } from 'node:fs/promises';
import { join } from 'node:path';
import { generatedVersion } from '../knowledge/generated.js';
import { VERSION } from '../version.js';
import { KNOWLEDGE_DIR as DIR, knowledgeDir, MOVED } from './../knowledge/paths.js';

/**
 * The shape a harness accepts back from a session hook.
 *
 * Three of them, because three conventions exist and a hook that prints the
 * wrong one is a hook that says nothing at all. Only the field the current
 * platform reads is emitted: Claude Code reads both `additional_context` and
 * `hookSpecificOutput` without deduplicating, so printing both says everything
 * twice.
 */
export type SessionResponse =
  | { hookSpecificOutput: { hookEventName: 'SessionStart'; additionalContext: string } }
  | { additional_context: string }
  | { additionalContext: string };

/** Which shape this harness expects, from what it puts in the environment. */
export function shapeFor(env: NodeJS.ProcessEnv, context: string): SessionResponse {
  if (env['CURSOR_PLUGIN_ROOT'] !== undefined) return { additional_context: context };
  if (env['CLAUDE_PLUGIN_ROOT'] !== undefined && env['COPILOT_CLI'] === undefined) {
    return { hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: context } };
  }
  // The SDK's own shape: Copilot CLI, and anything that has not said otherwise.
  return { additionalContext: context };
}

/** Enough of a file to hold the marker; never the whole knowledge base. */
const HEAD = 512;

/**
 * How many files to look at.
 *
 * This runs on every session start, before anybody has asked for anything, so
 * its whole budget is a directory listing and a few short reads. It builds
 * nothing, parses nothing, and calls no model: generation costs tokens and
 * spending somebody's tokens because they opened a terminal is not a thing a
 * plugin may do.
 */
const MAX_FILES = 12;

async function firstBytes(path: string): Promise<string | null> {
  const handle = await open(path, 'r').catch(() => null);
  if (handle === null) return null;
  try {
    const buffer = Buffer.alloc(HEAD);
    const { bytesRead } = await handle.read(buffer, 0, HEAD, 0);
    return buffer.subarray(0, bytesRead).toString('utf8');
  } catch {
    return null;
  } finally {
    await handle.close().catch(() => undefined);
  }
}

/**
 * The standing instruction: which skills a job takes, and in what order.
 *
 * Each `SKILL.md` description says when it applies; this adds the order, and
 * says the skills join a process that is already running rather than claiming
 * the start of every task. A second standing instruction that competes with an
 * installed planning process is what this replaced.
 *
 * Fixed text. It is not a scan, it parses nothing and it calls no model, so the
 * session costs what it always cost: a directory listing and at most twelve
 * short reads.
 *
 * The same words are in `USING.md`, because the harnesses without a session
 * hook read that file instead.
 */
const STANDING = [
  'ui-consistency — for anything the end user will see, these join the phases of',
  'whatever process is already running, and run the phases themselves when none is.',
  'Use them without being asked.',
  '',
  '- A new page or feature, or a refactor across pages:',
  '  ui-consistency:finding-patterns → ui-consistency:planning',
  '  → ui-consistency:implementing → ui-consistency:verifying',
  '- A small change to one page: finding-patterns, its reduced branch',
  '  → implementing → verifying. The check is never the part that gets dropped.',
  '- Checking code already written: verifying.',
  '- Can it be read, can it be used without a mouse — contrast, focus, keyboard,',
  '  a field and its label, text alternatives, target size:',
  '  ui-consistency:accessibility, with or without a phase around it.',
  '',
  'If a spec or plan for this work already exists, add to it instead of starting',
  'another. Decide by the order the skills carry and report what settled each',
  'decision; ask only where it ties and the change reaches outside the task.',
].join('\n');

/**
 * The one line a session may be told about this project's knowledge base.
 *
 * Two states are worth saying something about, and no others:
 *
 * - the knowledge base is in the old location.
 * - files in it were generated by an older plugin than the one now running, so
 *   what they say may no longer be what this version would say.
 *
 * Everything else is silence. A message on every session that is not news is
 * how a plugin trains people to skip its output.
 */
export async function sessionContext(rootDir: string): Promise<string | null> {
  // The old location is read, and saying so is the point: a rename whose
  // fallback works silently leaves people on the old path forever, and the
  // session hook is where they already look.
  const { dir, legacy } = await knowledgeDir(rootDir);
  const entries = await readdir(dir).catch(() => null);
  const files = (entries ?? []).filter((name) => /\.md$/i.test(name)).sort();

  const said = [STANDING];

  const versions = new Set<string>();
  for (const name of files.slice(0, MAX_FILES)) {
    const head = await firstBytes(join(dir, name));
    if (head === null) continue;
    const version = generatedVersion(head);
    if (version !== null && version !== VERSION) versions.add(version);
  }

  if (legacy) said.push(`ui-consistency: ${MOVED}`);

  if (versions.size > 0) {
    said.push(
      [
        `ui-consistency: the generated part of ${DIR}/ was written by`,
        `plugin ${[...versions].sort().join(', ')}; this is ${VERSION}.`,
        'Nothing generates those files any more, and nothing replaces them: what a',
        'task counts is evidence for the decisions it reports, and goes with the task.',
        'Those files are obsolete and can be deleted. The one thing worth carrying out',
        'of one is a decision somebody made — and that goes wherever the process you',
        'are running already records decisions, not into a directory of this plugin.',
      ].join(' '),
    );
  }

  return said.join('\n\n');
}

interface Payload {
  cwd?: unknown;
}

/**
 * The `SessionStart` adapter. Never throws, and says nothing by default.
 */
export async function sessionResponse(stdin: string): Promise<SessionResponse | null> {
  if (SILENCED()) return null;
  let cwd = process.cwd();
  try {
    const parsed: unknown = JSON.parse(stdin);
    const payload = parsed as Payload;
    if (typeof payload?.cwd === 'string' && payload.cwd !== '') cwd = payload.cwd;
  } catch {
    // A payload that will not parse is not a reason to say nothing — the
    // project is still there, and the working directory is still readable.
  }

  const context = await sessionContext(cwd).catch(() => null);
  if (context === null) return null;

  return shapeFor(process.env, context);
}
